### ISSUE TITLE
Dependabot preview support

### ISSUE THREAD

**Issue by glensc** [fastify/github-action-merge-dependabot#11]
## 🐛 Bug Report

Looks like the user `dependabot[bot]` does not always match, here's an example:
- https://github.com/eventum/eventum/pull/994

## To Reproduce

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *node version*: 10, 12, 13
- *fastify version*: >=2.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by mcollina** [comment]
This is to be used with the new dependabot implementation (not dependabot-preview). This is on purpose.

dependabot-preview support this feature natively.

**Comment by mcollina** [comment]
We should document this in the readme.

**Comment by simoneb** [comment]
I'll add it to https://github.com/fastify/github-action-merge-dependabot/pull/10

**Comment by simoneb** [comment]
Done

**Comment by simoneb** [comment]
@glensc closing this issue because we won't support dependabot preview.

**Comment by glensc** [comment]
> This is to be used with the new dependabot implementation (not dependabot-preview). This is on purpose.
> 
> dependabot-preview support this feature natively.

not sure what you mean by "this", I'm looking for a flow to merge automatically submitted PR once CI passes. currently, I have to issue `@dependabot` command in comments for it to merge.

so, dependabot-preview can merge, but not automatically...

**Comment by simoneb** [comment]
"this" is this action. It does not support dependabot preview. see the updated documentation.

**Comment by glensc** [comment]
my question was on what is the "this" that dependabot supports natively.

but now found the auto-merge setting, it was under user setting, not project setting:

- https://app.dependabot.com/accounts/xxx/settings

![image](https://user-images.githubusercontent.com/199095/109979904-12969180-7d08-11eb-9dfa-9793d1b30c52.png)

**Comment by glensc** [comment]
Thanks, pals, I'll switch to the native implementation.

The "preview" leads to believe it's newer than the native, seems it's not the case here.
