### ISSUE TITLE
v3 rollout

### ISSUE THREAD

**Issue by Eomm** [fastify/github-action-merge-dependabot#111]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

To complete the #103 we need to:

1. <del>define the shutdown end date for the external application. I would propose **31th March** or the 1st of April 😂 </del>
1. implement and release https://github.com/fastify/dependabot-merge-action-app/issues/105
2. then implement and release https://github.com/fastify/github-action-merge-dependabot/issues/110
3. then release v3 https://github.com/fastify/github-action-merge-dependabot/pull/107

**Comment by Eomm** [comment]
> define the shutdown end date for the external application. I would propose 31th March or the 1st of April 

Regarding this point: the application will not shout down. So users are not forced to update to v3

**Comment by simoneb** [comment]
We can consider shutting down the app at some point, but no sooner than after a reasonable time for users to upgrade, which will be a few months at least.
