### ISSUE TITLE
Provide major (and minor) tags

### ISSUE THREAD

**Issue by TonyRL** [fastify/github-action-merge-dependabot#112]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Provides major tag `v2` and possible `v3` in the future which tag to the latest appropriate commit.
(Side note: I saw you provides `v1` which tags to the same commit as `v1.0.0`)

### Motivation

As it is stated in GitHub Docs <https://docs.github.com/en/actions/creating-actions/releasing-and-maintaining-actions#example-developer-process>

> We recommend creating releases using semantically versioned tags – for example, `v1.1.3` – and keeping major (`v1`) and minor (`v1.1`) tags current to the latest appropriate commit. For more information, see "[About custom actions](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions)" and "[About semantic versioning](https://docs.npmjs.com/about-semantic-versioning).

**Comment by simoneb** [comment]
@salmanm this would be a good idea to include in the release automation work you're doing

**Comment by salmanm** [comment]
Sure, we could add a command like [this](https://github.com/nearform/optic-release-automation-action/blob/main/bump.js#L41) after release is [published successfully](https://github.com/nearform/optic-release-automation-action/blob/main/release.js#L65)

**Comment by simoneb** [comment]
@ja-bravo will look into this

**Comment by Fdawgs** [comment]
+1, this would further cut down on bot messages in the Fastify org feed.

**Comment by simoneb** [comment]
Yes I also agree it's a good idea, I remember we met discussing it in other issues. Nevertheless I want this to be automated, otherwise it's just additional manual effort that we have to put in whenever we do a release. Hence, support this in the release automation action we're working on

**Comment by simoneb** [comment]
Solved by https://github.com/nearform/optic-release-automation-action/pull/16

**Comment by simoneb** [comment]
It's not really solved yet, we need to use the action

**Comment by Eomm** [comment]
Published the v3 major and minor tag, but it is not fully automated.

Reopening
