### ISSUE TITLE
Change the default value for target from any to *

### ISSUE THREAD

**Issue by nuragic** [fastify/github-action-merge-dependabot#122]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Moving the discussion from #121 here:

As stated in the README:

> based on Semantic Versioning

`any` is not valid in SemVer, but we have `* `for that, so I guess we should replace `any` for `*`.

**Comment by Eomm** [comment]
At the moment `target: any` means:

> the action does not check the semver before approve&merge

Instead, `target: *` could mean:

> before approve&merge check if the semver has a right format

This is a different meaning for me.

A [quick search](https://github.com/search?q=github-action-merge-dependabot&type=code) about these GHA users let me think if all these repos rely on `semver`.

I would rename `any` to `disabled` instead

**Comment by simoneb** [comment]
again the main thing to consider here is supporting submodules which don't have a semver version as per https://github.com/fastify/github-action-merge-dependabot/issues/95

**Comment by simoneb** [comment]
see also conversation in #121 for context

**Comment by nuragic** [comment]
Right now `target: any` means _any_ target, so put in other words: the check is actually disabled, right? 

The `*` rename proposal was to align to the SemVer spec (as we state in the docs, `target` needs to be a valid SemVer identifier), because it literally means _any_ version.

However, given the submodule requirement (`target` is a git hash, so not a valid SemVer neither), the right thing to do IMHO would be to just leave target `undefined` by default, because it's an optional field and it doesn't really need to have a value, I think it would be easiest to understand in this way (no target by default, no check).

**Comment by simoneb** [comment]
Well the change is already merged but this issue is still open because it wasn't linked from the PR

**Comment by simoneb** [comment]
@nuragic can you please acknowledge the message above? If so, can you please close this issue?

**Comment by nuragic** [comment]
I agree about that it doesn't make sense to use `*` so I'll close it now. 

But I'd like to address this proposal. 

> Given the submodule requirement (target is a git hash, so not a valid SemVer neither), the right thing to do IMHO would be to just leave target undefined by default, because it's an optional field and it doesn't really need to have a value, I think it would be easiest to understand in this way (no target by default, no check).

Maybe in a new issue?

**Comment by simoneb** [comment]
Yes, thanks!

**Comment by nuragic** [comment]
Moved to #128
