### ISSUE TITLE
Manage semver-like formats

### ISSUE THREAD

**Issue by Eomm** [fastify/github-action-merge-dependabot#124]
When the user set the `target` option and the dependabot's PR is like the following:

```
chore(deps): bump nearform/optic-release-automation-action from 2.2.0 to 2.3
```

(note the `2.3` version)

The semver check fails.

We should be more resilient and be able to merge this PR too.

Ref https://github.com/fastify/github-action-merge-dependabot/issues/121#issuecomment-988013334

**Comment by simoneb** [comment]
and it should also keep working with submodules. see #98

**Comment by nuragic** [comment]
One approach is the one mentioned above by @Eomm; another approach would be to use the valid SemVer number, which is in this case `2.3.0`... would be that possible? It seems that we have that information in the pull requests opened by dependabot, e.g.

![Screenshot 2021-12-07 at 16 28 30](https://user-images.githubusercontent.com/1586378/145058578-b4b15651-2922-4698-aafd-82a44ca2bf57.png)

We're extracting the `2.3` from the title?

**Comment by simoneb** [comment]
> We're extracting the 2.3 from the title?

yes. I think the approach is to use coerce / loose options from the semver library

**Comment by nuragic** [comment]
What I'm saying is that IMHO the right thing to do would be to have the valid SemVer number even in the title, e.g.
> chore(deps): bump actions/setup-node from 2.4.1 to 2.5.0
https://github.com/nearform/optic-release-automation-action/pull/15

**Comment by simoneb** [comment]
we can't, we're not creating those PRs, dependabot is

**Comment by nuragic** [comment]
Yeah of course hehe I know but there's no way to fix that by changing some config here?

https://github.com/fastify/github-action-merge-dependabot/blob/main/.github/dependabot.yml

**Comment by simoneb** [comment]
no

**Comment by simoneb** [comment]
@Eomm can you do a manual release of the action? We'll have to wait until next week before publishing this action using release automation, because the current version is not capable of auto updating if we create the non-semver tags

**Comment by Eomm** [comment]
Yes, I have checked the `main` dist folder and it is all aligned.

Publishing...
