### ISSUE TITLE
GITHUB_TOKEN is readonly and can't be used to merge the PR

### ISSUE THREAD

**Issue by simoneb** [fastify/github-action-merge-dependabot#13]
[This change](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/) caused this action to not be usable to merge PRs as described in the docs, because the built-in GITHUB_TOKEN is now readonly in pull_request events.

[This article](https://securitylab.github.com/research/github-actions-preventing-pwn-requests) describes two alternatives to have a read/write token.

There is still an option to use a personal access token or a GitHub app though.

Ultimately, this action is not broken but the documentation should show how to use it successfully. The documentation is now broken because of the readonly behavior of the default GITHUB_TOKEN.

**Comment by mcollina** [comment]
Unfortunately using a personal access token is extremely risky as it would have access to more than one repo and action and therefore it would be way more risky than the temporary token Github Actions used before.

I think we should use pull_request_target and update all the repos :/.

**Comment by simoneb** [comment]
I suggest we consider using the workflow_run instead, which can isolate the automerge in a standalone workflow file which can be used as-is everywhere, without requiring modifications to the main CI workflow.

**Comment by mcollina** [comment]
That would be better, yes.

**Comment by inigo-garcia** [comment]
Adding extra information about possible solutions:

https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
