### ISSUE TITLE
Regression in 3.1.0: Error: Cannot use 'in' operator to search for '' in false

### ISSUE THREAD

**Issue by richardsheridan** [fastify/github-action-merge-dependabot#172]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.1.0

### Node.js version

??? whatever your action pulls

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

A basic use-case in my repository stopped working after dependabot bumped it from 3.0.2 to 3.1.0.  An error message reads `Error: Cannot use 'in' operator to search for '' in false`.  The only place that I see `false` in the output is for the default argument of the `approve-only` option.  Please see the relevant run: https://github.com/richardsheridan/trio-parallel/runs/5859944536?check_suite_focus=true#step:2:7

### Steps to Reproduce

I don't think my workflow and settings are anything extraordinary but it is the only steps to reproduce that I have: 

https://github.com/richardsheridan/trio-parallel/blob/e9d713c3b86434d8bc9f9a528e0017cdb49f4aa3/.github/workflows/ci.yml#L265-L277

**Comment by guilhermelimak** [comment]
Just FYI I'm taking a look at this issue.

**Comment by simoneb** [comment]
@richardsheridan this should be addressed in 3.1.1, I would appreciate if you could confirm, thanks!

**Comment by richardsheridan** [comment]
Got the green check! ✅

https://github.com/richardsheridan/trio-parallel/pull/275

Thanks @simoneb @guilhermelimak for the quick turnaround and thanks fastly for the great action!

**Comment by simoneb** [comment]
Amazing, thanks
