### ISSUE TITLE
Action run fails with error

### ISSUE THREAD

**Issue by xobotyi** [fastify/github-action-merge-dependabot#18]
## 🐛 Bug Report
Not shure if it should be here or in the app repo but doing it here.

During workflow run action fails with 503 error, but nevertheless merges the PR.

You can see failed workflow here: https://github.com/xobotyi/node-beanstalk/actions/runs/656962760

## To Reproduce

Just run the action

## Expected behavior

Action should complete w\o errors.

**Comment by simoneb** [comment]
This should be fixed in https://github.com/fastify/dependabot-merge-action-app/commit/d1d505413d27134bcef4f05538bcc9fcca4f5383. No need to update the action, it's a change in the backing HTTP API.

**Comment by simoneb** [comment]
It should be fixed now, closing.
