### ISSUE TITLE
Specify engine

### ISSUE THREAD

**Issue by Uzlopak** [fastify/github-action-merge-dependabot#211]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

It would be useful to specify the minimum node version in the package.json

**Comment by climba03003** [comment]
I don't understand.
It should use the version in `action.yml`.
https://github.com/fastify/github-action-merge-dependabot/blob/f4ccf6c9cf2e8497e0def84477a28e47d20c6916/action.yml#L29-L31
