### ISSUE TITLE
Missing how to turn off the removed app

### ISSUE THREAD

**Issue by glensc** [fastify/github-action-merge-dependabot#239]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

> Turn off the [dependabot-merge-action-app](https://github.com/fastify/dependabot-merge-action-app/) ([ on 25 Nov 2021](https://github.com/fastify/dependabot-merge-action-app/tree/16fa942ee9b390d755efcdff28daa347da5aeaa3)) application.

please add steps for that into the readme.

**Comment by glensc** [comment]
I understand I need to revoke access given to that application. as if you boot it up again you would not have access to my project.

**Comment by glensc** [comment]
And the issue is about adding the instructions how to remove grant/permission (whatever the terminology is) in projects that have granted app an access.

**Comment by simoneb** [comment]
Once the app is removed there's no need to do anything else I suppose.

**Comment by glensc** [comment]
Are you saying if you delete the app, you can no longer regain the permissions to projects even if you re-instate the app? I.e for projects security the projects should remove permissions given the app with the v3 migration.

**Comment by simoneb** [comment]
Once deleted there's no reinstating. I'll keep this open until somebody with permissions on the org removes the app altogether.

**Comment by glensc** [comment]
I'm not asking what you are planning to do, I'm talking about theoretically from a security point of view.

**Comment by simoneb** [comment]
Read the first sentence above.

**Comment by simoneb** [comment]
In any case, uninstall the app from your org/repos and you're good.

**Comment by glensc** [comment]
> it's fair to assume you know how to uninstall it.

it's not fair to assume that. and that's what I'm trying to indicate here. users might not even realize they have left some access open.

but fine, I give up then.

**Comment by simoneb** [comment]
You can send a PR with more detailed instructions
