### ISSUE TITLE
Automerge fails when author of a commit is not defined

### ISSUE THREAD

**Issue by marco-ippolito** [fastify/github-action-merge-dependabot#259]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.0.0

### Plugin version

3.2.2

### Node.js version

18.7.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.5.1

### Description

When automerging it checks if in the commit list there is a non-dependabot commit, by doing so it goes into uncaught exception if there is an unkown author commit.
![image](https://user-images.githubusercontent.com/36735501/185968258-9e2ddcc3-bed5-4add-95f2-edd311f6ca91.png)

### Steps to Reproduce

```
tap.test('should skip PR with non dependabot commit', async () => {
  const PR_NUMBER = Math.random()
  const { action, stubs } = buildStubbedAction({
    payload: {
      pull_request: {
        user: {
          login: BOT_NAME,
        },
        number: PR_NUMBER,
      },
    },
    inputs: { PR_NUMBER },
  })

  stubs.prCommitsStub.resolves([
    {
      author: undefined
    },
  ])

  await action()

  sinon.assert.calledOnce(stubs.prCommitsStub)
  sinon.assert.calledWithExactly(
    stubs.logStub.logWarning,
    'PR contains non dependabot commits, skipping.'
  )
  sinon.assert.notCalled(stubs.approveStub)
  sinon.assert.notCalled(stubs.mergeStub)
})`
``

### Expected Behavior

I think it should check if the commit has a known author.

**Comment by simoneb** [comment]
The intended behavior is that an unknown author is considered the same as an author who's not dependabot
