### ISSUE TITLE
@v1 conflicting docs

### ISSUE THREAD

**Issue by glensc** [fastify/github-action-merge-dependabot#27]
On @v1, the readme says `Inputs: GITHUB_TOKEN`, but then the example below says `github-token: ${{secrets.github_token}}`
- https://github.com/fastify/github-action-merge-dependabot/tree/40ad9cca4590e7f38130222835c6c68a7d93a6a7#readme

of course, users copy the example, rather than read the preceding block!

This ends up failing job:
```
Warning: Unexpected input(s) 'github-token', valid inputs are ['GITHUB_TOKEN']
Run fastify/github-action-merge-dependabot@v1
  with:
    github-token: ***
Error: Resource not accessible by integration
```

ref (probably private):
- https://github.com/eventum/eventum/pull/1066/checks?check_run_id=2384356122

**Comment by mcollina** [comment]
v1 is not working anymore, does this refer to v2 as well?

**Comment by simoneb** [comment]
Don't use V1, due to changes in the permissions of the built-in GITHUB_TOKEN it won't work anymore. See https://www.nearform.com/blog/github-dependabot-automation/

**Comment by simoneb** [comment]
The reason why your build is failing is not wrong documentation, but the aforementioned change in token permissions.

**Comment by glensc** [comment]
this bug report is explicitly about `v1`. `v2` docs are in sync.

I'm no longer using v1, you can find my pr linked. I was a good citizen and reported a bug upstream.

**Comment by simoneb** [comment]
As I mentioned the error you were getting is unrelated.

**Comment by glensc** [comment]
bug what I reported is there:

![image](https://user-images.githubusercontent.com/199095/115309062-68b67b80-a174-11eb-8186-6d236aa1b374.png)

![image](https://user-images.githubusercontent.com/199095/115309098-753ad400-a174-11eb-83da-812d8c23d011.png)
