### ISSUE TITLE
500 error on action run

### ISSUE THREAD

**Issue by glensc** [fastify/github-action-merge-dependabot#28]
```
Run fastify/github-action-merge-dependabot@v2.0.0
Error: Request failed with status code 500: {"statusCode":500,"code":"ERR_ASSERTION","error":"Internal Server Error","message":"{\"message\":\"Not Found\",\"documentation_url\":\"docs.github.com/rest/reference/apps#get-a-repository-installation-for-the-authenticated-app\"}"}
```

- https://github.com/eventum/eventum/pull/1066/checks?check_run_id=2388297970 (might be private)

yaml:
- https://github.com/eventum/eventum/blob/5c3365a29dbe8d18be634d736326886cc47cce1c/.github/workflows/ci.yml#L138-L146

Is this 500 error from GitHub and I should just retry, or it's from your application, can't understand it from the logs.

**Comment by simoneb** [comment]
My best guess is you have not installed the GitHub application on the repository. See https://github.com/fastify/github-action-merge-dependabot#usage

**Comment by mcollina** [comment]
We should provide a better error message in this case.

**Comment by simone-sanfratello** [comment]
Solved https://github.com/fastify/dependabot-merge-action-app/pull/15
