### ISSUE TITLE
Deprecation warning: set-output command

### ISSUE THREAD

**Issue by curthipster** [fastify/github-action-merge-dependabot#295]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

My workflow using `fastify/github-action-merge-dependabot@v3` is resulting in warning Annotations like this:

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by climba03003** [comment]
It is upstream issue of `dependabot/fetch-metadata`

https://github.com/dependabot/fetch-metadata/blob/ae81da92fd7d7c12569dc41f8106827abc90eadc/src/dependabot/output.ts#L49-L61

**Comment by jeffwidman** [comment]
Sorry for the delay, I just merged the upstream PR and will cut a release later today
