### ISSUE TITLE
Filtering automerge emails to reduce noise

### ISSUE THREAD

**Issue by salmanm** [fastify/github-action-merge-dependabot#3]
## 🚀 Feature Proposal

To POST a comment on the PR **after approval** with a specific message that can be used in email filters. 😬 

Something like 👇 
![image](https://user-images.githubusercontent.com/2510597/102865805-4d549180-445c-11eb-8e61-9ae8089d6c77.png)

- auto merge action approves the PR
- merges the PR
- posts a comment "DEPENDABOT-AUTO-MERGED"

## Motivation

Now that almost all fastify repos are auto-merging dependabot PRs. It occurred to me that it could simplify/reduce noise further if we could set email filters and mark emails from auto-merged PRs "as read".

Of course, we could set a filter based on the sender "dependabot[bot] <notifications@github.com>", but it does not catch the "approval" and "merge" emails. See the example screenshot.

![image](https://user-images.githubusercontent.com/2510597/102865429-bf78a680-445b-11eb-9d94-afbf14a02b7c.png)

The first email comes from `dependabot[bot]` and correctly gets marked as read. However, the next two comes from `github-actions[bot]` and stays unread. 

@fastify/plugins thoughts?

**Comment by Eomm** [comment]
I assume you would not like to mark as read all the emails from "github-actions[bot]", but only from the "approve-bot", is it right?

If so, I would use the [`body` parameter](https://octokit.github.io/rest.js/v18#pulls-create-review) in the approval review, instead of a new comment.
Or could we customize the commit email/name via some git commands?

**Comment by salmanm** [comment]
> but only from the "approve-bot"

Exactly, only the one's generated by this action

> body parameter in the approval review

This would correctly mark the approval mail as read. However, next mail is merge notification, which will mark the mail thread unread again.

> could we customize the commit email/name

The bot's name is associated with the `GITHUB_TOKEN` and can not be changed AFAIK. See [here](https://github.community/t/change-bots-name-avatar/18349/2).

**Comment by jsumners** [comment]
This might make it harder to see the items I can dismiss without reading in the GitHub notification panel. I have all emails from GitHub notifications turned off and only use the notification panel.

**Comment by Eomm** [comment]
> This would correctly mark the approval mail as read. However, next mail is merge notification, which will mark the mail thread unread again.

I get the point: it is necessary that the last item of the thread can be recognized to mark as read.

> The bot's name is associated with the GITHUB_TOKEN and can not be changed AFAIK. See here.

Oh, so it should necessary to build a bot to accomplish it.

----

From my side, the message at the end doesn't bother me 👍

**Comment by mcollina** [comment]
I have a feeling this would not make our life easier.

**Comment by zekth** [comment]
I only use the notification panel like @jsumners said. I don't think this would improve anything, at least to me.
