### ISSUE TITLE
Option an option to use github's auto-merge feature

### ISSUE THREAD

**Issue by shouichi** [fastify/github-action-merge-dependabot#301]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Add an option to use github's auto-merge feature.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request

This feature request may by related to https://github.com/fastify/github-action-merge-dependabot/issues/251.

### Motivation

We don't use github actions and CI status checks are required to merge. When dependabot creates a PR, github-action-merge-dependabot immediately tries to merge the PR but fails because the required status checks are not successful. One idea is to use github's auto-merge feature and let github merge PRs instead of github-action-merge-dependabot.

**Comment by simoneb** [comment]
Would you be interested in sending a PR for this?

**Comment by shouichi** [comment]
Mmm, it won't happen soon to be honest. I'm not familiar with github actions and its api. But I found that to enable auto-merge PRs, we need to use graphql api https://github.com/orgs/community/discussions/24719#discussioncomment-3245222.

**Comment by shouichi** [comment]
Well, I played with the github api and opened a PR https://github.com/fastify/github-action-merge-dependabot/pull/302. I confirmed that it works but need to add tests. @simoneb Could you help me to finish the PR? Thank you.

**Comment by shouichi** [comment]
@simoneb Hello, added test to #302. Could you take a look?
