### ISSUE TITLE
Add milestone to pull request

### ISSUE THREAD

**Issue by glensc** [fastify/github-action-merge-dependabot#34]
## 🚀 Feature Proposal

Similarly to adding labels to pull request
would be nice to add a milestone to the pull request once it's merged.

The system must be smart enough to find open milestone to add to pull request as it would be too dull to make a commit for each time release is made and new milestone needs to be used.

## Motivation

Projects may use labels to mark pull requests to a specific milestone.

The current workaround is to add a milestone manually once the pull request is merged.

## Example

- https://github.com/eventum/eventum/pull/1115#event-4784333547

**Comment by simoneb** [comment]
Would you like to send a PR?

**Comment by glensc** [comment]
@simoneb no
