### ISSUE TITLE
Error: Request failed with status code 400

### ISSUE THREAD

**Issue by qelphybox** [fastify/github-action-merge-dependabot#39]
Hi! Action doesn't work for me.  I used it like in README 
https://github.com/qelphybox/hakeshonassybot/runs/2702331035?check_suite_focus=true

Then [I tried to change](https://github.com/qelphybox/hakeshonassybot/commit/83c161937706cac59ca485b9b0c10d4c7bacec06) `api-url` to one from action.yml defaults from master branch
https://github.com/qelphybox/hakeshonassybot/runs/2703535764?check_suite_focus=true

Always i get ```Error: Request failed with status code 400:```

Did I do something wrong?

**Comment by simoneb** [comment]
Did you install the github application?

**Comment by qelphybox** [comment]
> Did you install the github application?

Aaaah, no, did not :(

**Comment by mcollina** [comment]
@simoneb we should provide better error messages for this case.

**Comment by qelphybox** [comment]
> @simoneb we should provide better error messages for this case.

That would be great!

**Comment by qelphybox** [comment]
> Did you install the github application?

I installed, and it works now, thx a lot. I can submit PR to improve error message

**Comment by simoneb** [comment]
> I can submit PR to improve error message

Yes please!
