### ISSUE TITLE
Remove `node_modules` folder

### ISSUE THREAD

**Issue by piranna** [fastify/github-action-merge-dependabot#4]
`node_modules` folder should not be added to the git repository except for some very strange corner cases, remove it and add to the `.gitignore` file.

**Comment by salmanm** [comment]
https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action

> From your terminal, commit your action.yml, index.js, node_modules, package.json, package-lock.json, and README.md files. If you added a .gitignore file that lists node_modules, you'll need to remove that line to commit the node_modules directory.

**Comment by piranna** [comment]
That doesn't makes sense... maybe it's done for performance. Anyway, I find it better the second alternative they propose of publishing a bundle, we could create it with husky :-)

**Comment by piranna** [comment]
Or a github action adding a new commit too :-)
