### ISSUE TITLE
Auto-Merge Flag to Limit to Minor/Patch Updates

### ISSUE THREAD

**Issue by austins** [fastify/github-action-merge-dependabot#44]
## 🚀 Feature Proposal

Add an optional input flag (i.e. target) to only auto-merge on major, minor, patch updates based on Semantic Versioning.

- Default value would be major.
- Setting to minor would include both minor and patch updates.
- Setting to patch would only auto-merge on patch updates.

## Motivation

Major updates may have breaking changes. Being able to auto-merge to only minor or patch updates will allow PRs for major versions to be manually approved and merged.

## Example

~~~
steps:
  - uses: fastify/github-action-merge-dependabot@v2.1.1
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      target: minor
~~~

**Comment by fahric** [comment]
- [ ]  Add a new optional flag called `target` and set default value to `major`
- [ ] work out the semantic version of the PR (ex from title) and compare the target flag
- [ ] only call api if the flag and the PR version match
- [ ] add tests

**Comment by austins** [comment]
Thank you!
