### ISSUE TITLE
Missing LICENSE file in repository

### ISSUE THREAD

**Issue by Fdawgs** [fastify/github-action-merge-dependabot#6]
Hi there!

`package.json` states that this repo is MIT licensed however said license file is missing.
I would open a pull request but it seems like a pretty important document that is best suited to a member of the Fastify group adding?

**Comment by penx** [comment]
closed in https://github.com/fastify/github-action-merge-dependabot/commit/b7b0c824941cdc50340525f1de21bfb2dcd579e6
