### ISSUE TITLE
Does This Work with Multiple "needs"?

### ISSUE THREAD

**Issue by alexdlaird** [fastify/github-action-merge-dependabot#603]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I've previously seen this issue, [as reported here](https://github.com/fastify/github-action-merge-dependabot/issues/561), but I resolved it.

```Pull request is in unstable status```

Now, I'm seeing it again after changing my Workflow, so I'm wondering if there's something incorrect about my new configuration / is it incompatible with this plugin? I don't think it should be, but unsure what else is going on. It'd be great if we could get _any_ sort of additional context on this error, as it's so broad it makes it hard to even know where to troubleshoot, but my understanding is the error message actually comes directly from GitHub, so it seems like perhaps we can't get any more specificity on it.

Anyway, I use this plugin on 10+ of my projects, all with the same config, no issues with the Dependabot integration, it works like a charm. Recently, I modified two of my projects to have two parallel steps, `build` and `validate`, and they _both_ need to finish (and pass) before the automerge can process. Every since then, I get the "unstable status" message again. Is this not supported, or is something wrong in my new config (which you can see [here](https://github.com/alexdlaird/java-ngrok/blob/f458f62bd85c7f02b1fe135c3af838318ae19863/.github/workflows/build.yml#L61))? [Here is what the config looked](https://github.com/alexdlaird/java-ngrok/blob/e6ffbcbbe11709a358d44f76e785eb0e84cd7c8b/.github/workflows/build.yml#L65) like _before_ I made the changes and split up my workflows into multiple steps. Maybe the issue is that the `validate` step it depends on now lives in a separate `.yml` file? Any way around that, if so?

Here is [an example failing pulling request](https://github.com/alexdlaird/java-ngrok/pull/99). It wants to merge in to `main`, where I have branch protection rules, and yes the two actions of `build` and `validate` are set as required status checks. Anything else I should be looking at?

**Comment by simoneb** [comment]
I see that you have Code Scanning enabled, as a required check. I guess that's the reason.

**Comment by alexdlaird** [comment]
A required check that's passing ... is code scanning not compatible with this plugin and somehow different than a regular required check, or what am I missing there?

**Comment by simoneb** [comment]
It's a required check that can't be waited for. If we try to merge the PR before that's completed, which is most likely what happened here, you'll get that error. I don't see a solution apart from making it a non-required check. Within a workflow you can't "need" a job that lives outside the workflow.

**Comment by alexdlaird** [comment]
Ah, great explanation. Thanks for providing the clarity! Will remove.
