### ISSUE TITLE
ci: Generate dist automatically

### ISSUE THREAD

**Issue by zekth** [fastify/github-action-merge-dependabot#62]
## 🚀 Feature Proposal

Using the `{{ secrets.GITHUB_TOKEN }}` in github actions we can commit directly in the PR or the master branch; that could be interesting to do automatically on PRs, therefore when merging into master the `dist` folder will be all the time up to date.

## Motivation

Simplify the build and release process

**Comment by simoneb** [comment]
I don't like the idea of making changes to the repository in CI. There are husky hooks in the repo, contributors should make sure they are run. PR reviews will catch if the dist folder has not been generated.

**Comment by zekth** [comment]
Closing as we rely on `husky` to generate those on commits.
