### ISSUE TITLE
GitHub actions workflows are not triggered when PRs are merged by this action

### ISSUE THREAD

**Issue by simoneb** [fastify/github-action-merge-dependabot#8]
## 🐛 Bug Report

GitHub actions workflows are not triggered when PRs are merged by this action.

See the long discussion in https://github.com/nearform/fastify-secrets-core/issues/59, which is using this action.

The behavior is by design, to avoid recursive workflow triggers.

## Expected behavior

We would like to have workflows triggered by merges done by this action. One of the options is to use a GitHub application to do so. It may be worth researching how to do that.

**Comment by simoneb** [comment]
We intend to address this issue by implementing a new behavior which allows to use GitHub's built-in automerge feature, implemented in #9 .

**Comment by glensc** [comment]
Could this be documented, how to configure GitHub's built-in auto-merge feature in this project readme?

I only could find "Allow auto-merge" under https://github.com/org/project/settings "Merge button" and even that does not seem to behave like documented:
- https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request


![image](https://user-images.githubusercontent.com/199095/109919058-b5c3b880-7cc0-11eb-9efb-f972e118b097.png)

![image](https://user-images.githubusercontent.com/199095/109919160-ead00b00-7cc0-11eb-9429-ce43bc231a25.png)

**Comment by simoneb** [comment]
GitHub's automerge behaves as documented as far as I have seen. Added docs about this here https://github.com/fastify/github-action-merge-dependabot/pull/10

**Comment by glensc** [comment]
@simoneb thanks!

maybe the browser plugin I use is somehow interfering:
- https://github.com/josephfrazier/octopermalinker
