### ISSUE TITLE
How do I exclude packages from GitHub Actions?

### ISSUE THREAD

**Issue by itsmeboy0** [fastify/github-action-merge-dependabot#96]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

For example, putting `fastify/github-action-merge-dependabot` doesn't seem to work neither does.

**Comment by simoneb** [comment]
The logic we use to detect the "package" name is a bit fuzzy and may not work consistently outside of the npm ecosystem we're using. Can you link a PR that didn't work for you or post the name of the branch of the dependabot PR?

**Comment by sameer-coder** [comment]
@itsmeboy0 Exclude is working fine for me. Make sure you are using only the package name in the exclude option value

Example:
```yaml
exclude: 'react'
```

If it still doesn't work, can you please provide a sample PR demonstrating the issue?

**Comment by itsmeboy0** [comment]
Hmm, looking back at my repo it looks like everything works fine now. Maybe it is a downtime or something I have overlooked.
